/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.City.City;
import model.City.CommunityList;
import model.City.HouseList;
import model.Users.Person;
import model.Users.DummyData;
import model.Users.PersonList;
/**
 *
 * @author nikhilbindal
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String userType = "System Administrator";
    private CommunityList communityList;
    private City city;
    private HouseList houseList;
    public Login() {
        initComponents();
        DummyData dummyData = new DummyData();
        communityList = new CommunityList();
        city = new City();
        houseList = new HouseList();
//        dummyData.createPerson("System", "Admin", 987654320, "SysAdmin", "admin");
//        dummyData.createPerson("Hospital", "Admin", 987654321, "HospitalAdmin", "admin");
//        dummyData.createPerson("City", "Admin", 987654322, "CityAdmin", "admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblCloseApp = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        roleDropdown = new javax.swing.JComboBox<>();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(102, 102, 255));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCloseApp.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCloseApp.setForeground(new java.awt.Color(255, 255, 255));
        lblCloseApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseApp.setText("X");
        lblCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseAppMouseClicked(evt);
            }
        });
        headerPanel.add(lblCloseApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, -1));

        lblLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login Here!");
        headerPanel.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 386, -1));

        loginPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 85));

        lblLoginAs.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(153, 153, 153));
        lblLoginAs.setText("Login As:");
        loginPanel.add(lblLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 157, -1, -1));

        roleDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System Administrator", "City Administrator", "Hospital Administrator", "Doctor", "Personal" }));
        roleDropdown.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 153, 102)));
        roleDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleDropdownActionPerformed(evt);
            }
        });
        loginPanel.add(roleDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 193, 244, 35));

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setText("Username :");
        loginPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 246, -1, -1));

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 153, 102)));
        loginPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 282, 244, 32));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblPassword.setText("Password :");
        loginPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 352, -1, -1));

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 153, 102)));
        loginPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 388, 243, 35));

        btnLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        loginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 462, 243, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAppMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblCloseAppMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        if(username.isBlank() || username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username field is empty");
            return;
        } else if(password.isBlank() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password field is empty");
            return;
        }
        
        if (userType.equals("System Administrator")) {
            if (!username.equals("SysAdmin")) {
                JOptionPane.showMessageDialog(this, "Invalid Username!");
            } else if(!password.equals("admin")) {
                JOptionPane.showMessageDialog(this, "Invalid Password!");
            } else {
                JOptionPane.showMessageDialog(this, "Login Successful!");
                Dashboard dashboard = new Dashboard(city, communityList, houseList);
                dashboard.setVisible(true);
                this.dispose();
            }
        }
        
        if (userType.equals("City Administrator")) {
            if (!username.equals("CityAdmin")) {
                JOptionPane.showMessageDialog(this, "Invalid Username!");
            } else if(!password.equals("admin")) {
                JOptionPane.showMessageDialog(this, "Invalid Password!");
            } else {
                JOptionPane.showMessageDialog(this, "Login Successful!");
//                CityAdminDashboard dashboard = new CityAdminDashboard(city, communityList, houseList);
//                dashboard.setVisible(true);
                this.dispose();
            }
        }
        
        if (userType.equals("Hospital Administrator")) {
            if (!username.equals("HospitalAdmin")) {
                JOptionPane.showMessageDialog(this, "Invalid Username!");
            } else if(!password.equals("admin")) {
                JOptionPane.showMessageDialog(this, "Invalid Password!");
            } else {
                JOptionPane.showMessageDialog(this, "Login Successful!");
                HospitalAdminDashboard dashboard = new HospitalAdminDashboard();
                dashboard.setVisible(true);
                this.dispose();
            }
        }
        
        if (userType.equals("Patient")) {
            JOptionPane.showMessageDialog(this, "User doesnot exist!");
//            if (!username.equals("Patient")) {
//                JOptionPane.showMessageDialog(this, "Invalid Username!");
//            } else if(!password.equals("admin")) {
//                JOptionPane.showMessageDialog(this, "Invalid Password!");
//            } else {
//                JOptionPane.showMessageDialog(this, "Login Successful!");
//                Dashboard dashboard = new Dashboard();
//                dashboard.setVisible(true);
//                this.dispose();
//            }
        }
        
        if (userType.equals("Doctor")) {
            JOptionPane.showMessageDialog(this, "User doesnot exist!");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void roleDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleDropdownActionPerformed
        // TODO add your handling code here:
        this.userType = roleDropdown.getSelectedItem().toString();
    }//GEN-LAST:event_roleDropdownActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblCloseApp;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JComboBox<String> roleDropdown;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
